language: node_js

node_js:
  - "0.10"

before_script:
  - npm install -g bower tsd gulp
  - bower install

script:
  - gulp
  - ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS
