language: node_js

node_js:
  - "4.1"

before_script:
  - npm install -g bower tsd gulp
  - bower install

script:
  - gulp lint
  - gulp build
  - ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS
