language: node_js

node_js:
  - "4.1"

before_script:
  - npm install -g bower tsd gulp
  - bower install

  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp lint
  - gulp build
  - ./node_modules/karma/bin/karma start --single-run --browsers Chrome_travis_ci
