/// <reference path='./../typings/tsd.d.ts' />
/// <reference path="./services/devise.ts"/>
/// <reference path='app.ts' />
/// <reference path='./decorators/directive.ts'/>
/// <reference path='./login/LoginButtonDirective.ts'/>
/// <reference path='./login/LoginService.ts'/>
/// <reference path='./login/LoginCtrl.ts'/>
/// <reference path='./registration/RegistrationCtrl.ts'/>
/// <reference path='./test/TestCtrl.ts'/>
/// <reference path='./login/Login.ts'/>
