/* global System */
System.config({
  defaultJSExtensions: true,
  paths: {
    'jquery': 'libs/jquery.min.js',
    'bootstrap': 'libs/bootstrap.min.js',
    'metis-menu': 'libs/metisMenu.min.js',
    'jquery.ui.core': 'libs/core.js',
    'jquery.ui.widget': 'libs/widget.js',
    'jquery.ui.mouse': 'libs/mouse.js',
    'jquery.ui.sortable': 'libs/sortable.js',
    'jquery.iframe-transport': 'libs/jquery.iframe-transport.js',
    'jquery.fileupload': 'libs/jquery.fileupload.js',
    'jquery-cloudinary': 'libs/jquery.cloudinary.js',
    'angular': 'libs/angular.min.js',
    'angular-ui-router': 'libs/angular-ui-router.min.js',
    'angular-resource': 'libs/angular-resource.min.js',
    'angular-cookies': 'libs/angular-cookies.min.js',
    'angular-translate': 'libs/angular-translate.min.js',
    'angular-translate-storage-local': 'libs/angular-translate-storage-local.min.js',
    'angular-translate-storage-cookie': 'libs/angular-translate-storage-cookie.min.js',
    'angular-translate-loader-partial': 'libs/angular-translate-loader-partial.min.js',
    'js-data': 'libs/js-data.min.js',
    'js-data-http': 'libs/js-data-http.min.js',
    'js-data-angular': 'libs/js-data-angular.min.js',
    'angularjs-color-picker': 'libs/angularjs-color-picker.min.js',
    'devise': 'libs/devise-min.js',
    'angular-ui-grid': 'libs/ui-grid.min.js',
    'angular-breadcrumb': 'libs/angular-breadcrumb.min.js',
    'angular-ui-tinymce': 'libs/tinymce.js',
    'angular-ui-sortable': 'libs/sortable.min.js',
    'angular-chart': 'libs/angular-chart.min.js',
    'chart': 'libs/Chart.min.js',
    'maaas-config': 'app/ngConstants.js',
    'angular-animate': 'libs/angular-animate.min.js',
    'angular-bootstrap': 'libs/ui-bootstrap.min.js'
  }
});
